version: '2.1'

services:

  router1:
    image: elalitte/debian_client01
    cap_add:
      - ALL
    networks:
      local_net:
        ipv4_address: 172.16.200.101

  client1:
    image: elalitte/debian_client01
    cap_add:
      - ALL
    networks:
      local_net:
        ipv4_address: 172.16.200.102

  hacker1:
    image: elalitte/debian_client01
    cap_add:
      - ALL
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      local_net:
        ipv4_address: 172.16.200.103

networks:
  local_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.200.0/24
          gateway: 172.16.200.101
